const std = @import("std");
const M31 = @import("../field/m31.zig").M31;
const CirclePoint = @import("point.zig").CirclePoint;
const CircleDomain = @import("domain.zig").CircleDomain;

/// A coset of a circle subgroup: { offset ⊕ h : h ∈ H } where H is the
/// subgroup generated by `step` (order 2^log_size). Used to evaluate on
/// points strictly outside the polynomial's original subgroup, so that
/// low-degree tests (FRI) are meaningful.
pub const CircleCoset = struct {
    offset: CirclePoint,
    step: CirclePoint,
    log_size: u32,

    pub fn new(offset: CirclePoint, step: CirclePoint, log_size: u32) CircleCoset {
        return .{ .offset = offset, .step = step, .log_size = log_size };
    }

    pub fn size(self: CircleCoset) usize {
        return @as(usize, 1) << @intCast(self.log_size);
    }

    pub fn at(self: CircleCoset, index: usize) CirclePoint {
        std.debug.assert(index < self.size());
        return self.offset.add(self.step.mulScalar(@as(u64, @intCast(index))));
    }

    /// A coset of the canonical subgroup of order 2^log_size, offset by the
    /// full-circle generator so that none of its points lie in the subgroup.
    pub fn standard(log_size: u32) CircleCoset {
        const offset = CirclePoint.generator();
        const step = CirclePoint.generatorWithOrder(log_size);
        return CircleCoset.new(offset, step, log_size);
    }

    /// Halves the coset under doubling: doubles offset and step, so
    /// `at(i).double()` lands in the halved coset.
    pub fn half(self: CircleCoset) CircleCoset {
        std.debug.assert(self.log_size > 0);
        return CircleCoset.new(self.offset.double(), self.step.double(), self.log_size - 1);
    }

    /// The conjugate coset: `-initial - <step>`.
    pub fn conjugate(self: CircleCoset) CircleCoset {
        return CircleCoset.new(self.offset.neg(), self.step.neg(), self.log_size);
    }

    /// The canonic half-coset of a circle domain of order 2^log_size:
    /// the points `{ B^(2^(30-log_size)) ⊕ <B^(2^(32-log_size))> }`, where
    /// `B = generator().neg()`.
    ///
    /// The full circle domain is this coset disjoint-union its conjugate. The
    /// ordering matches the convention used by stwo's O(n log n) circle FFT,
    /// and avoids the identity point (where circle interpolation divides by y).
    ///
    /// Note: `generator()` and its negation differ by an element of order 4,
    /// so `canonicHalf` is only guaranteed to match stwo's traversal for
    /// `log_size <= 28`; the FFT is only exercised up to that size.
    pub fn canonicHalf(log_size: u32) CircleCoset {
        std.debug.assert(log_size >= 1 and log_size <= 28);
        const gen = CirclePoint.generator().neg();
        const offset = gen.mulScalar(@as(u64, 1) << @intCast(30 - log_size));
        const step = gen.mulScalar(@as(u64, 1) << @intCast(32 - log_size));
        return CircleCoset.new(offset, step, log_size - 1);
    }
};

test "circle coset properties" {
    const coset = CircleCoset.standard(4);
    try std.testing.expectEqual(@as(usize, 16), coset.size());
    // all points on the circle
    for (0..coset.size()) |i| {
        try std.testing.expect(coset.at(i).onCircle());
    }
    // points are distinct
    for (0..16) |i| {
        const p = coset.at(i);
        for (0..i) |j| {
            const q = coset.at(j);
            try std.testing.expect(!(p.x.eq(q.x) and p.y.eq(q.y)));
        }
    }
    // half(): double of coset points lands in the halved coset
    const h = coset.half();
    try std.testing.expectEqual(@as(usize, 8), h.size());
    for (0..8) |i| {
        const doubled = coset.at(i).double();
        try std.testing.expect(doubled.x.eq(h.at(i).x));
        try std.testing.expect(doubled.y.eq(h.at(i).y));
    }
}

test "circle coset avoids canonical subgroup" {
    const dom = CircleDomain.standard(3);
    const coset = CircleCoset.standard(3);
    for (0..8) |i| {
        const p = coset.at(i);
        var in_domain = false;
        for (0..8) |j| {
            const q = dom.get(j);
            if (p.x.eq(q.x) and p.y.eq(q.y)) in_domain = true;
        }
        try std.testing.expect(!in_domain);
    }
}

test "circle coset conjugate negates points" {
    const coset = CircleCoset.canonicHalf(4);
    const conj = coset.conjugate();
    try std.testing.expectEqual(@as(usize, 8), conj.size());
    for (0..conj.size()) |i| {
        try std.testing.expect(conj.at(i).x.eq(coset.at(i).x));
        try std.testing.expect(conj.at(i).y.eq(coset.at(i).y.neg()));
    }
}

test "circle coset canonicHalf properties" {
    var log_size: u32 = 1;
    while (log_size <= 8) : (log_size += 1) {
        const coset = CircleCoset.canonicHalf(log_size);
        try std.testing.expectEqual(@as(usize, 1) << @intCast(log_size - 1), coset.size());
        // all points on the circle and distinct
        const n = coset.size();
        for (0..n) |i| {
            try std.testing.expect(coset.at(i).onCircle());
            const p = coset.at(i);
            for (0..i) |j| {
                const q = coset.at(j);
                try std.testing.expect(!(p.x.eq(q.x) and p.y.eq(q.y)));
            }
        }
        // the domain coset ++ conjugate has 2^log_size distinct points
        const conj = coset.conjugate();
        const total = n * 2;
        var idx: usize = 0;
        while (idx < total) : (idx += 1) {
            const p = if (idx < n) coset.at(idx) else conj.at(idx - n);
            for (0..idx) |j| {
                const q = if (j < n) coset.at(j) else conj.at(j - n);
                try std.testing.expect(!(p.x.eq(q.x) and p.y.eq(q.y)));
            }
        }
    }
}
